feat: add external-sites app
owncloud/web-extensions pull request #13
Opened 2024-07-23 13:35 UTC by JammingBen

See README.md file.

refs https://github.com/owncloud/web/issues/7260

2024-07-23 13:41 UTC, JammingBen commented
@kulmann This has the minimum feature set for now, so no special things like restricted access for specific groups/roles like in https://github.com/owncloud/web/pull/7934. I don't really feel like we need it at the moment, what do you think?

2024-07-23 18:12 UTC, dschmidt commented on packages/web-app-external-sites/tsconfig.json
> +      "typeRoots" : ["./node_modules/@types"]
Most probaly not needed

2024-07-24 04:35 UTC, kulmann requested changes

2024-07-24 04:35 UTC, kulmann commented on packages/web-app-external-sites/README.md
> +      color: "#0D856F",
```suggestion
      "color": "#0D856F",
```

2024-07-24 04:35 UTC, kulmann commented on packages/web-app-external-sites/README.md
> +The `name` will appear in the app menu, while `url` specifies the url which will be opened or embedded. `target` can either be `external` or `embedded`. Choose `external` if the site should be opened
Could you please add a statement that `embedded` only works if the server of the target url allows embedding via their `CORS` server settings? Together with a rule of thumb `Just test it. If embedded doesn't work for the specified url then you need to use external instead.`.

2024-07-24 04:35 UTC, kulmann commented on packages/web-app-external-sites/README.md
> +The following options are optional:
```suggestion
The following attributes are optional:
```

2024-07-24 04:35 UTC, kulmann commented on packages/web-app-external-sites/README.md
> +- `color` _(string)_ - specifies the Hex color codes of the menu item.
```suggestion
- `color` _(string)_ - specifies the Hex color codes of the icon background of the menu item.
```

2024-07-24 04:35 UTC, kulmann commented on packages/web-app-external-sites/README.md
> +- `priority` _(number)_ - specifies the order of the menu item.
Please add some words about the range and what happens if it's left out.

2024-07-24 04:35 UTC, kulmann commented on packages/web-app-external-sites/src/App.vue
> +  <div class="external-site-container">
This should be a `<main>` tag for a11y reasons... we have a button to jump to the `main` content. Editor apps have that from `AppWrapper.vue` but standalone apps need to define it.

2024-07-24 10:06 UTC, kulmann approved these changes
awesome 🥳

2024-07-24 10:13 UTC, merged